version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: ct-visit-manager:latest
    env_file:
      - .env
    environment:
      - PORT=5005
      - MONGODB_URI=mongodb://ct-visit-manager-db:27017/ct-visit-manager-db
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - ct-visit-manager-db

  ct-visit-manager-db:
    image: mongo:3.6.4
