version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - PORT=5005
    ports:
      - "5005:5005"
    depends_on:
      - contact-tracing-db

  contact-tracing-db:
    image: mongo:3.6.4
